number:
  # Current state on how we are treating the front button 0 cal low, 1 cal high, 2 normal reset filter, 3 button disabled
  - platform:       template
    id:             button_mode
    name:           button mode
    internal:       True
    mode:           box
    optimistic:     true
    min_value:      0
    max_value:      3
    initial_value:  0
    step:           1
    restore_value:  yes
    on_value:
      then:
        - lambda: |-
            if(x==0){
              id(yellow_led).turn_on().set_effect("Slow_Blink").perform();
            }
            if(x==1){
              id(yellow_led).turn_on().set_effect("Fast_Blink").perform();
            }
            if(x==2){
              id(yellow_led).turn_off().perform();
            }
            if(x==3){
              id(yellow_led).turn_off().perform();
            }

binary_sensor:

  # Formerly the wi-fi button, used for calibration and resetting the filter
  - id:             !extend wifi_button
    name:           Front Button
    on_release:
      then:
        - lambda: |-
            if(id(button_mode).state==0){
                id(min_water_level).make_call().set_value(id(water_level).state).perform();
                id(yellow_led).turn_off().perform();
                id(button_mode).make_call().set_value(1).perform();
            }
            else if(id(button_mode).state==1){
                id(max_water_level).make_call().set_value(id(water_level).state).perform();
                id(yellow_led).turn_off().perform();
                if(id(front_filter).state==1){
                  id(button_mode).make_call().set_value(2).perform();
                } else {
                  id(button_mode).make_call().set_value(3).perform();
                }

            }
            else if(id(button_mode).state==2){
                id(filter_changed_button).press();
                id(yellow_led).turn_off().perform();
            }
            else if(id(button_mode).state==3){
                // Do nothing
            }
