esphome:
  platformio_options:
    board_build.flash_mode:   dio
    board_build.flash_size:   4MB
    board_build.f_flash:      40000000L
  project:
    name:                     petlibro.plwf105
    version:                  "1.2.4"

esp32:
  board:                      esp32-c3-devkitm-1
  variant:                    ESP32C3
  framework:
    type:                     esp-idf
