defaults:
  # You should choose to set either hide_oz or hide_ml to true to reduce the number of sensors present in HA
  hide_oz:              "false"
  hide_ml:              "false"

  hide_debug:           "true"

  name:                 petlibro-plwf105
  friendly_name:        PetLibro PLWF105

  api_encryption_key:   ""
  ota_password:         ""

  wifi_ssid:            !secret wifi_ssid
  wifi_password:        !secret wifi_password

  time_platform:        sntp
  timezone:             America/Chicago

dashboard_import:
  package_import_url:   github://taylorfinnell/petlibro-esphome/plwf105/plwf105.yaml@master
  import_full_config:   true

esphome:
  name:                 "${name}"
  friendly_name:        "${friendly_name}"

api:
  encryption:
    key:                "${api_encryption_key}"

logger:
  level:                debug

ota:
  platform:             esphome
  password:             "${ota_password}"

wifi:
  ssid:                 "${wifi_ssid}"
  password:             "${wifi_password}"

captive_portal:

sensor:
  - platform:           uptime
    name:               Uptime

  - platform:           wifi_signal
    name:               WiFi Signal
    update_interval:    60s

text_sensor:
  - platform:           version
    name:               ESPHome Version

  - platform:           wifi_info
    ip_address:
      name:             IP
    ssid:
      name:             SSID
    bssid:
      name:             BSSID

time:
  - platform:           "${time_platform}"
    id:                 sntp_time
    timezone:           "${timezone}"

packages:
  # ESP32 platform definition
  platform:             !include platform.yaml
  # GPIO pins
  gpio:                 !include gpio.yaml
  # Light entities
  lights:               !include lights.yaml
  # Pump entities
  pump:                 !include pump.yaml
  # Water Level
  water:                !include water.yaml
  # Convert WiFi button to use as a calibration tool
  button:               !include button.yaml
  # Track filter expiration
  filter:               !include filter.yaml
  # Calibrate water levels from the device directly
  calibrate_water:      !include calibrate_water.yaml
  # Track how much water is being drunk
  drunk_water:          !include drunk_water.yaml
  # Run the pump on an repeating interval rather then all the time
  pump_timer:           !include pump_timer.yaml

#### In Loving Memory Of Tuxey Putnam 2006-2024 ######
